### ISSUE TITLE
我导入了300MB左右的视频，好像软件会直接卡住

### ISSUE THREAD

**Issue by cccRaim** [Rainbow-Dreamer/ascii-converter#1]

**Comment by Rainbow-Dreamer** [comment]
你使用的是32位的版本还是64位的？一般来说32位的版本处理比较大的视频可能内存不够。我现在使用64位的版本（也就是文件名中没有32位的那个）转换了一个300多MB的视频的前300帧，软件没有出现卡顿的现象，并且成功转换。

**Comment by cccRaim** [comment]
> 你使用的是32位的版本还是64位的？一般来说32位的版本处理比较大的视频可能内存不够。我现在使用64位的版本（也就是文件名中没有32位的那个）转换了一个300多MB的视频的前300帧，软件没有出现卡顿的现象，并且成功转换。

感谢回复，我这边是想转换整个视频，取消了帧区间，可能是这个原因？

**Comment by Rainbow-Dreamer** [comment]
你取消帧区间的方法是把`视频转换帧区间`的参数框里的内容去掉吗？如果是的话，那应该是可以正常转换整个视频的。我现在也这样测试了一下，是可以正常运行的。左下角的信息栏有实时转换的进度显示。

**Comment by cccRaim** [comment]
> 你取消帧区间的方法是把`视频转换帧区间`的参数框里的内容去掉吗？如果是的话，那应该是可以正常转换整个视频的。我现在也这样测试了一下，是可以正常运行的。左下角的信息栏有实时转换的进度显示。

是的，直接去掉。我回家再试试吧，现在我用的远程控制，好像直接整个屏幕黑了一下，我回家看看到底怎么回事

**Comment by Rainbow-Dreamer** [comment]
好的

**Comment by cccRaim** [comment]
不知道怎么回事，就直接正在处理第2帧就卡住了，然后占了14GB内存，看preview文件夹里也只有1张图片。
运行后整个电脑exploer重启，chrome直接崩了。不知道是不是我AMD芯片的原因- -

**Comment by Rainbow-Dreamer** [comment]
这个确实是底层帧数转换算法的问题，我目前已经更新了版本，改成实时读取并转换帧数了，基本不会占用任何内存，你可以下载最新版本试试，感谢反馈issue

**Comment by cccRaim** [comment]
> 这个确实是底层帧数转换算法的问题，我目前已经更新了版本，改成实时读取并转换帧数了，基本不会占用任何内存，你可以下载最新版本试试，感谢反馈issue

辛苦辛苦，好像已经可以了，真的非常感谢

**Comment by Rainbow-Dreamer** [comment]
不客气
