### ISSUE TITLE
It's not working.

### ISSUE THREAD

**Issue by LeePC** [Rainbow-Dreamer/ascii-converter#2]
The window turns on and closes again. How can I fix this?

**Comment by Rainbow-Dreamer** [comment]
What is the system you are using? This software currently on support Windows. If you are working on Windows, be sure to download the full version zip file from the link that is provided at download section of README, unzip it and open Ascii Converter.exe. This repository itself does not provide compiled executables on its own, only source code.

**Comment by LeePC** [comment]
OS : Windows 10
RAM : 32G
graphic card : GTX 1060 6G

**Comment by LeePC** [comment]
https://user-images.githubusercontent.com/8704225/224961546-ceeee825-b743-426a-9923-665a0e20046a.mp4

Demo Videos

**Comment by LeePC** [comment]
https://user-images.githubusercontent.com/8704225/224961907-5db90e69-5453-46be-9337-a57606775d97.mp4

Demo Videos

**Comment by Rainbow-Dreamer** [comment]
Thanks for the feedback, there is a bug here, I already fixed it and update the version, you can download it from the same link and try it again.
